version: "3.7"
services:
  wind-api-v2:
    build: .
    env_file: .env
    ports:
      - '8003:80'
    command: uvicorn infrared_wrapper_api.api.main:app --host 0.0.0.0 --port 80 --reload
    networks:
      &network_mode
      - bridgenet
    volumes:
      - ./:/app
  
  redis-wind-api-v2:
    container_name: redis-wind-api-v2
    image: redis:6.2-alpine
    ports:
      - ${REDIS_PORT:-6379}:6379
    restart: "always"
    command: redis-server --requirepass ${REDIS_PASSWORD}  --appendonly yes
    networks: *network_mode
    volumes:
      - "./redis/data:/data"
  
  celery-worker-wind-api-v2:
    container_name: celery-worker-wind-api-v2
    build: .
    restart: "always"
    command: celery -A infrared_wrapper_api.tasks worker --loglevel=info
    networks: *network_mode
    env_file:
      - .env
    volumes:
      - ./:/app
    depends_on:
      - wind-api-v2
      - redis-wind-api-v2
  
  flower-wind-api-v2:
    container_name: flower-wind-api-v2
    build: .
    command: celery -A infrared_wrapper_api.tasks flower --port=5555
    networks: *network_mode
    ports:
      - '5556:5555'
    env_file:
      - .env
    depends_on:
      - wind-api-v2
      - redis-wind-api-v2
      - celery-worker-wind-api-v2

networks:
  bridgenet:
    driver: bridge